# Generated by Django 2.2.6 on 2019-11-18 19:00

import case.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_condition_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AirConditionTypeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=case.models.EntranceGroundCustomization)),
                ('air_condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.AirConditionType')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturalDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architectural_design', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.BasementCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.BasementCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.BasementCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.BasementCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.BasementCustomization)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='CeillingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceilling_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.ElevatorCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.ElevatorCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.ElevatorCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.ElevatorCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.ElevatorCustomization)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.EntranceGroundCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.EntranceGroundCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.EntranceGroundCustomization)),
                ('picture4', models.ImageField(blank=True, null=True, upload_to=case.models.EntranceGroundCustomization)),
                ('picture5', models.ImageField(blank=True, null=True, upload_to=case.models.EntranceGroundCustomization)),
                ('other_entrance_ground', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FacadeRealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='FacadeImgCustomization')),
                ('other_facade', models.CharField(max_length=20)),
                ('facade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Facade')),
            ],
        ),
        migrations.CreateModel(
            name='FencesCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fences_condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.GardenCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.GardenCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.GardenCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.GardenCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.GardenCustomization)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ground_SidewalkCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_sidewalk', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HoashGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.HoashGroundCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.HoashGroundCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.HoashGroundCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.HoashGroundCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.HoashGroundCustomization)),
                ('other_ground', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='InsulationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulationType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Outside_Fences_7oash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.Outside_Fences_7oashCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.Outside_Fences_7oashCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.Outside_Fences_7oashCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.Outside_Fences_7oashCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.Outside_Fences_7oashCustomization)),
                ('ground_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OutsideFencesGround', to='case.Ground_SidewalkCondition')),
                ('sidewalk_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OutsideFencesSidewalk', to='case.Ground_SidewalkCondition')),
            ],
        ),
        migrations.CreateModel(
            name='PublicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_location_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='اسم رقم التواصل')),
                ('contact_number', models.BigIntegerField(verbose_name='رقم التواصل')),
                ('agent_name', models.CharField(default='وزارة الإسكان', editable=False, max_length=15)),
                ('location', models.URLField(blank=True, null=True, verbose_name='الموقع')),
                ('coordinator_note', models.TextField(blank=True, default='لا توجد', null=True, verbose_name='الملاحظات ( إذا وجدت )')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المالك')),
                ('deed_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الصك')),
                ('deed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصك')),
                ('notary', models.CharField(blank=True, max_length=50, null=True, verbose_name='كتابة عدل')),
                ('outline_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم المخطط')),
                ('outline_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المخطط')),
                ('piece_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم القطعة')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة')),
                ('license_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الرخصة')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرخصة')),
                ('dataEntry_note', models.TextField(blank=True, null=True, verbose_name='الملاحظات ( إذا وجدت )')),
                ('street_condition_pic', models.ImageField(blank=True, null=True, upload_to=case.models.StreetConditionCustomization, verbose_name='صورة الشارع')),
                ('nearest_street_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم أقرب شارع')),
                ('distance_nearest_street', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='على بعد')),
                ('before_entring_building_note', models.TextField(blank=True, null=True, verbose_name='ملاحظات قبل دخول العقار')),
                ('after_entring_building_note', models.TextField(blank=True, null=True, verbose_name='ملاحظات بعد دخول العقار')),
                ('roof_note', models.TextField(blank=True, null=True, verbose_name='ملاحظات السطح و الملحق العلوي')),
                ('real_estate_age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عمر العقار')),
                ('architectural_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.ArchitecturalDesign', verbose_name='التصميم المعماري')),
                ('basement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Basement', verbose_name='القبو')),
                ('ceiling_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.CeillingType', verbose_name='نوع الأسقف')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.City', verbose_name='المدينة')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Elevator', verbose_name='المصعد')),
                ('facade', models.ManyToManyField(through='case.FacadeRealEstate', to='case.Facade', verbose_name='الواجهات')),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Garden', verbose_name='الحديقة')),
                ('hoash_ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.HoashGround', verbose_name='أرضية الحوش')),
                ('insulation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.InsulationType', verbose_name='أنواع العزل')),
                ('neighborhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Neighborhood', verbose_name='الحي')),
                ('outside_fences', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Outside_Fences_7oash', verbose_name='الأسوار الخارجية والأحواش')),
                ('public_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.PublicLocation', verbose_name='الموقع العام')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Region', verbose_name='المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.ReceptionistGroundCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.ReceptionistGroundCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.ReceptionistGroundCustomization)),
                ('picture4', models.ImageField(blank=True, null=True, upload_to=case.models.ReceptionistGroundCustomization)),
                ('picture5', models.ImageField(blank=True, null=True, upload_to=case.models.ReceptionistGroundCustomization)),
                ('other_receptionist_ground', models.CharField(blank=True, max_length=50, null=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.RoomsGroundCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.RoomsGroundCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.RoomsGroundCustomization)),
                ('picture4', models.ImageField(blank=True, null=True, upload_to=case.models.RoomsGroundCustomization)),
                ('picture5', models.ImageField(blank=True, null=True, upload_to=case.models.RoomsGroundCustomization)),
                ('other_rooms_ground', models.CharField(blank=True, max_length=50, null=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='SkeletonStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeleton_structure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_for', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StreetCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_condition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TankInsulatorCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_insulator_condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_condition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WallCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WindowDoorCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_door_condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.SmallIntegerField(default=0)),
                ('double_wall', models.BooleanField(default=False)),
                ('double_glass', models.BooleanField(default=False)),
                ('gibs_in_roof', models.BooleanField(default=False)),
                ('hidden_lighting', models.BooleanField(default=False)),
                ('stairs', models.BooleanField(default=False)),
                ('electric_garage', models.BooleanField(default=False)),
                ('normal_garage', models.BooleanField(default=False)),
                ('doors', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('elevator_count', models.SmallIntegerField(default=0)),
                ('arabic_bathroom', models.BooleanField(default=False)),
                ('arabic_bathroom_count', models.SmallIntegerField(default=0)),
                ('heater', models.BooleanField(default=False)),
                ('heater_count', models.SmallIntegerField(default=0)),
                ('westorn_bathroom', models.BooleanField(default=False)),
                ('westorn_bathroom_count', models.SmallIntegerField(default=0)),
                ('air_condition_type', models.ManyToManyField(through='case.AirConditionTypeUnit', to='case.AirConditionType')),
                ('entrance_ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.EntranceGround')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Floor')),
                ('inside_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_inside_door', to='case.Door')),
                ('outside_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_outside_door', to='case.Door')),
                ('receptionist_ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.ReceptionistGround')),
                ('rooms_ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.RoomsGround')),
                ('unit_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.UnitCondition')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.UnitType')),
            ],
        ),
        migrations.CreateModel(
            name='TopGarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.TopGarageCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.TopGarageCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.TopGarageCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.TopGarageCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.TopGarageCustomization)),
                ('wall_ceiling_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WallCondition')),
                ('window_door_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WindowDoorCondition')),
            ],
        ),
        migrations.CreateModel(
            name='SwimPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.FilterCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.FilterCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.FilterCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.FilterCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.FilterCustomization)),
                ('filter_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.FilterCondition')),
                ('ground_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground_SidewalkCondition')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.RoofCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.RoofCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.RoofCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.RoofCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.RoofCustomization)),
                ('fences_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.FencesCondition')),
                ('ground_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground_SidewalkCondition')),
                ('tank_insulator_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.TankInsulatorCondition')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to=case.models.RealEstateDocumentCustomization)),
                ('realEstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.RealEstate')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='roof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Roof', verbose_name='السطح'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='skeleton_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.SkeletonStructure', verbose_name='الهيكل الأنشائي'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='slope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Slope', verbose_name='المنسوب'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='street_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.StreetCondition', verbose_name='الشوارع'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='swim_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.SwimPool', verbose_name='المسبح'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='top_garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.TopGarage', verbose_name='الملحق العلوي'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='utility',
            field=models.ManyToManyField(to='case.Utility', verbose_name='الخدمات'),
        ),
        migrations.CreateModel(
            name='OutsideGarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.OutsideGarageCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.OutsideGarageCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.OutsideGarageCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.OutsideGarageCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.OutsideGarageCustomization)),
                ('accessories_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsideDarage_accessories_condition', to='case.WallCondition')),
                ('wall_ceiling_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsideDarage_wall_ceiling_condition', to='case.WallCondition')),
                ('windows_doors_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WindowDoorCondition')),
            ],
        ),
        migrations.AddField(
            model_name='outside_fences_7oash',
            name='wall_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WallCondition'),
        ),
        migrations.CreateModel(
            name='Hallways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to=case.models.HallwaysCustomization)),
                ('picture2', models.ImageField(upload_to=case.models.HallwaysCustomization)),
                ('picture3', models.ImageField(upload_to=case.models.HallwaysCustomization)),
                ('picture4', models.ImageField(upload_to=case.models.HallwaysCustomization)),
                ('picture5', models.ImageField(upload_to=case.models.HallwaysCustomization)),
                ('ground_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground_SidewalkCondition')),
                ('illumination_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.FilterCondition')),
                ('wall_roof_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WallCondition')),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='ground_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground_SidewalkCondition'),
        ),
        migrations.AddField(
            model_name='garden',
            name='illumination_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_illumination_condition', to='case.FilterCondition'),
        ),
        migrations.AddField(
            model_name='garden',
            name='system_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_system_condition', to='case.FilterCondition'),
        ),
        migrations.AddField(
            model_name='floor',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.RealEstate'),
        ),
        migrations.AddField(
            model_name='facaderealestate',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.RealEstate'),
        ),
        migrations.AddField(
            model_name='entranceground',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.FilterCondition'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='illumination_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_illumination_condition', to='case.FilterCondition'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='ventilation_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevator_ventilation_condition', to='case.FilterCondition'),
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_direction_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('north_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('west_direction_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('west_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('south_direction_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('south_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('east_direction_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('east_length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.RealEstate')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Status')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='realEstate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case.RealEstate'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ManyToManyField(through='case.CaseStatus', to='case.Status'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ManyToManyField(through='case.UserCase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basement',
            name='ground_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Ground_SidewalkCondition'),
        ),
        migrations.AddField(
            model_name='basement',
            name='ventilation_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.FilterCondition'),
        ),
        migrations.AddField(
            model_name='basement',
            name='wall_ceiling_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.WallCondition'),
        ),
        migrations.AddField(
            model_name='airconditiontypeunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Unit'),
        ),
    ]
