# Generated by Django 2.2.6 on 2019-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='real_estate',
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='east_direction_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='شرق'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='east_length',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='north_direction_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='شمال'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='north_length',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='south_direction_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='جنوب'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='south_length',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='west_direction_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='غرب'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='west_length',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='بطول'),
        ),
    ]
