# Generated by Django 2.2.6 on 2019-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20191123_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.AddField(
            model_name='realestate',
            name='east_direction_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='شرق'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='east_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='بطول'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='north_direction_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='شمال'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='north_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='بطول'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='south_direction_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='جنوب'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='south_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='بطول'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='west_direction_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='غرب'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='west_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='بطول'),
        ),
    ]
