# Generated by Django 2.2.6 on 2019-11-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20191123_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='east_direction_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شرق'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='east_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='north_direction_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شمال'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='north_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='south_direction_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جنوب'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='south_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بطول'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='west_direction_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='غرب'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='west_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بطول'),
        ),
    ]
